# .github/workflows/greeting.yml

name: 'Simple Greeting Workflow'

# Controls when the action will run.
on:
  # Triggers the workflow on push events for the main branch
  push:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "greet"
  greet_job:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: 'Checkout repository code'
        uses: actions/checkout@v4

      # This is the step that contains your email address in its name
      - name: '23f2002900@ds.study.iitm.ac.in'
        run: echo "Hello, world! This step is uniquely named."

      - name: 'Show current directory'
        run: ls -la
